name: reactive_ble_mobile
description: Official Android and iOS implementation for the flutter_reactive_ble plugin.
version: 4.0.1
homepage: https://github.com/LEMUSADR000/flutter_reactive_ble.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependency_overrides:
  reactive_ble_platform_interface:
    git:
      url: https://github.com/LEMUSADR000/flutter_reactive_ble.git
      ref: 9ab32e5f8eacdb99441fe013ecb6462ebe5c35bb
      path: packages/reactive_ble_platform_interface

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.14

flutter:
  plugin:
    platforms:
      android:
        package: com.signify.hue.flutterreactiveble
        pluginClass: ReactiveBlePlugin
      ios:
        pluginClass: ReactiveBlePlugin
