name: flutter_reactive_ble
description: Reactive Bluetooth Low Energy (BLE) plugin that can communicate with multiple devices
version: 4.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: reactive_ble_mobile
      ios:
        default_package: reactive_ble_mobile

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  functional_data: ^1.0.0
  meta: ^1.3.0
  pedantic: ^1.11.1
  reactive_ble_mobile:
    git:
      url: https://github.com/LEMUSADR000/flutter_reactive_ble.git
      ref: 8198115d95c8c2e5e7939365cec424cc2637e81c
      path: packages/reactive_ble_mobile
  reactive_ble_platform_interface:
    git:
      url: https://github.com/LEMUSADR000/flutter_reactive_ble.git
      ref: 9a849f9e6246a73f7a36f8023c0d150a44c85833
      path: packages/reactive_ble_platform_interface

dev_dependencies:
  build_runner: ^2.1.0
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2
  mockito: ^5.0.14
  
