name: flutter_reactive_ble
description: Reactive Bluetooth Low Energy (BLE) plugin that can communicate with multiple devices
version: 4.0.1
homepage: https://github.com/LEMUSADR000/flutter_reactive_ble.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: reactive_ble_mobile
      ios:
        default_package: reactive_ble_mobile

dependency_overrides:
  reactive_ble_mobile:
    git:
      url: https://github.com/LEMUSADR000/flutter_reactive_ble.git
      ref: 9ab32e5f8eacdb99441fe013ecb6462ebe5c35bb
      path: packages/reactive_ble_mobile

  reactive_ble_platform_interface:
    git:
      url: https://github.com/LEMUSADR000/flutter_reactive_ble.git
      ref: 9ab32e5f8eacdb99441fe013ecb6462ebe5c35bb
      path: packages/reactive_ble_platform_interface


dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  functional_data: ^1.0.0
  meta: ^1.3.0
  pedantic: ^1.11.1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2
  mockito: ^5.0.14
  
